# Q1
1. Write function which takes two parameters account no and name of the user.
Check if the account number is valid. Account no is valid only if it is a 4 digit number less than 5000
Check if the name is valid. Name is valid if all characters are alphabets and no numbers or special chars in the name
If both name and 'acc no' are valid return True
If acc no is invalid return a message string saying “Account no is invalid”
if name is invalid return None

In [ ]:
def name(acc_n,acc_num):
    if (acc_num<5000) and (acc_num>=1000):
        if acc_n.isalpha():
            return True
        else:
            return False
    else:
        return "Account no invalid"

name('Shiva#',4000)

False

# Q2.
WA function to calculate total salary given that
1. post      2. basic salary
rules:
post can be manager or employee
total sal = basic + TA + HRA
TA = 5000 for 'manager'
and TA = 10,000 for 'employee'
HRA = 20,000 for 'manager' and HRA = 12,000 for 'employee'

return total salary based on two parameters

In [ ]:
def sal(post,basic_sal):
    if post.lower()=='manager':
        total_sal=basic_sal+5000+20000
        return total_sal
    elif post.lower()=='employee':
        total_sal=basic_sal+10000+12000
        return total_sal
total_sal1=sal('employee',5000)
print(total_sal1)

27000

# Q3
WA function to rotate given string by 2 position to right

Ex.
s1=”IACSD”
Rotate by 2 place to right
“SDIAC”

In [ ]:
def shift(name):
    n=len(name1)
    n1=name1[n-2::]+name1[:n-2:]
    return n1

name1='IACSDCDACAKURDI'
print(shift(name1))

DIIACSDCDACAKUR

# Q4.  
Generalize above function to rotate string to right by n

In [ ]:
def shift1(name,n):
    name1=''
    for idx in range(len(name)):
        name1+=name[idx-n]
    return name1

print(shift1("IACSD",3))

CSDIA

# Q5.
Generalize above function to rotate string by n to right or left

In [ ]:
def shift1(name,n1):
    n=n1%len(name)
    print(n)
    name1=''
    name2=""
    for idx in range(len(name)):
        name1+=name[idx-n]
    name2=name[n::]+name[:n:]
    return name1,name2

v1,v2=shift1("IACSD",8)
print("Right shift")
print(v1)
print("Left shift")
print(v2)

3
Right shift
CSDIA
Left shift
SDIAC

# Q6.
WAP to count number of passengers in every airline. Here we are given dictionary of passanger id and airline id
Ex
input_dir ={'p1':'a1','p2':'a10','p89':'a1','p5':'a10'}
output: {'a1':2, 'a10':2}

In [ ]:
def air(dic1):
    l1=list(dic1.values())
    l2=[]
    for x in l1:
        l2.append(l1.count(x))
    se=set()
    for i,j in zip(l1,l2):
        se.add((i,j))
    print(se)


dict1={'p1':'a1','p2':'a10','p89':'a1','p5':'a10'}
air(dict1)

{('a1', 2), ('a10', 2)}

In [ ]:
def air1(dic1):
    l1=list(dic1.values())
    l2=set(l1)
    out={}
    for i in l2:
        out[i]=l1.count(i)
    return out

print(air1(dict1))

{'a10': 2, 'a1': 2}

# Q7.
given a list of strings.
every string is in format "Emp_name:Emp_id"
Emp_id is always a number
if emp_id is amstrong number then rotate emp_name 1 place to the right --> and print the emp_name
if emp_id is a prime no then print vowels from the employee name
in other cases print consonents from the emp name
Finally there should be print of every employee name as per given condition

In [ ]:
def que7(str1):
    s =str1.split(':')
    emp_name=s[0]
    emp_id=int(s[1])
    len_id= len(s[1])

    arm=0
    for i in s[1]:
        arm+=(int(i)**len_id)
    if(arm==emp_id):
        print("Armstrong")
        emp_name = emp_name[-1]+ emp_name[:-1]
        print(emp_name)
        print()
        print('-----------------')
        return

    #Check for prime
    vow='aeiou'
    for i in range(2,(int(emp_id**0.5)+1)):
        if (emp_id%i==0):
            for j in emp_name:
                if (j not in vow):
                    print(j,end="")
            break
    else:
        for j in emp_name:
            if (j in vow):
                print(j,end="")
    print()
    print('-----------------')

In [ ]:
list1= ["aditya:85"  , "Shivam:83", "atharav:153","Ajinkya:4" ]
for i in list1:
    que7(i)

dty
-----------------
ia
-----------------
Armstrong
vathara

-----------------
Armstrong
aAjinky

-----------------

# Q8.
Write a function which takes all details of a person as input in sequence and prints details as follows
(Hint: Think which type of parameter to be used for every option)
a. Take name and Print it in Camel Case
b. Take 10 digit Mobile No and print it appending +91
c. Take location as optional value. If not given then print India
d. Take Qualifications. Qualifications can be 1 or 2 or many.
Print all the passed qualifications one by one. Default qualification is "Human"

In [ ]:
#name
name=input("Enter name")
name=name.split(" ")
l1=[]
for i in range(len(name)):
    l1.append(name[i].capitalize())
name=" ".join(l1)
print(name)

Shivam Muluk

In [ ]:
#mob no
mob=int(input("Enter mobile number "))
mob=str(mob)
mob='+91'+ mob
print(mob)

Enter mobile number 2345678901
+912345678901

In [ ]:
def val(a,*args):
  if not args:
    print("hii")
  else:
    print("hello")

val(1)

hii

In [ ]:
def input_de(name,mob,loc='INDIA',*args):
    #name=input("Enter name")
    print("-------------------------------")
    name=name.split(" ")
    l1=[]
    for i in range(len(name)):
        l1.append(name[i].capitalize())
    name=" ".join(l1)
    print("Name in camel case : ",name)
    #mob=int(input("Enter mobile number "))
    mob=str(mob)
    mob='+91'+"-"+mob
    print("Mobile no : ",mob)
    if not args:
      print("Qualification : ",'Human')
    for i in args:
        print("Qualification : ",i)
    print("Location : ",loc)

name1=input("Enter name ")
mob1=int(input("Enter mob number "))

loc1=input("Enter Country ")
if loc1=='':
    input_de(name1,mob1)
else:
    input_de(name1,mob1,loc1,'10th','12th','Diploma','Degree')

Enter name shivam martand muluk
Enter mob number 976719619734
Enter Country Bharat
-------------------------------
Name in camel case :  Shivam Martand Muluk
Mobile no :  +91-976719619734
Qualification :  10th
Qualification :  12th
Qualification :  Diploma
Qualification :  Degree
Location :  Bharat

# Q9.
Create a function "cloth_details" with three arguments, color, shape and size. All three are optional and can be passed in any sequence by the user.

In [ ]:
def cloth_details(*,color='black',shape='Rectangle',size='XL'):
    print("color is = ",color)
    print("shape is = ",shape)
    print("size is = ",size)

cloth_details(color='Orange',size='L',shape='Circle')

color is =  Orange
shape is =  Circle
size is =  L

# 10.
 Create a calculator.py file
Create add(), subtract(), multiply(), divide(), power(), log() functions
Create a menu driven program to take values and operation as input from user and print result using these functions

Take ONLY integer inputs from user. If its not an integer then give Error message -> "WRONG Input: Please enter ONLY integer value"
Your program should not give "ValueError" while using int() function for any input from below, It should display YOUR error message
Enter a number : 10
Enter a number : 10.9
Enter a number : ABC
(Hint: Think about methods from string data type to check input as integer)

In [ ]:
def cal(num1,num2):
    if (num1.isdigit()) and (num2.isdigit()):
      num1=int(num1)
      num2=int(num2)
    else:
      return("WRONG Input: Please enter ONLY integer value")
    print("Enter choice \n 1.add \n 2.subtract \n 3.multiply \n 4.divide \n 5.power \n 6.log")
    choice=input("Enter your choice")
    var1=choice1(num1,num2,choice)
    return var1

def choice1(a,b,c):
  import math
  match c:
    case "1":
      return a+b
    case "2":
      return a-b
    case "3":
      return a*b
    case "4":
      return a/b
    case "5":
      return a**b
    case "6":
      return math.log(a,b)
    case _:
      return "Wrong choice entered"
number=input("Enter the number 1 :")
number2=input("Enter the number 2 :")
var=cal(number,number2)
print(var)

Enter the number 1 :44
Enter the number 2 :55
Enter choice
 1.add
 2.subtract
 3.multiply
 4.divide
 5.power
 6.log
Enter your choice6
0.9443161970817594

# Q11.
Write a function which finds average of given arguments. Minimum it takes two parameters and maximum it can take any number of arguments.
Finally it should return average of all arguments passed

Ex. avg(10,12)  return value 11
avg(3,4,5)  return value 4
avg(1,2,3,4,5,6,7,8,9,10) return value 5.5
Extra case
avg(1,2,avg(4,5,6)) return value 2.667 (roughly 8/3)

In [ ]:
def avg1(*args):
  sum1=sum(args)
  avg=sum1/len(args)
  return avg

var=avg1(1,2,avg1(4,5,6))
print("Average is : ",var)

Average is :  2.6666666666666665